title: Information About Me
author: Yadnesh Chaudhari
email: yadneshchauhdari6@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  HI!, Ia ma Yadnesh Chaudhari i am a web-developer. I code in .ts, .html, .js, .py
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
